// Vercel Serverless Function — runtime config for the static frontend.
// Reads env vars set per Vercel environment (Production / Preview / Development)
// and emits the full APJConfig object as JavaScript so existing pages can keep
// loading <script src="/api/config"></script> exactly like a static file.
//
// Vercel UI → Project → Settings → Environment Variables, set:
//   Production:
//     APJ_ENV = prod
//     APJ_API_BASE_URL = https://ktor-lagartosapp-production.up.railway.app
//     APJ_STRIPE_PUBLISHABLE_KEY = pk_live_...
//   Preview:
//     APJ_ENV = stage
//     APJ_API_BASE_URL = https://ktor-lagartosapp-stage.up.railway.app
//     APJ_STRIPE_PUBLISHABLE_KEY = pk_test_...

module.exports = function handler(req, res) {
  const ENV = process.env.APJ_ENV || 'prod';
  const API_BASE_URL =
    process.env.APJ_API_BASE_URL ||
    (ENV === 'stage'
      ? 'https://ktor-lagartosapp-stage.up.railway.app'
      : 'https://ktor-lagartosapp-production.up.railway.app');
  const STRIPE_PUBLISHABLE_KEY = process.env.APJ_STRIPE_PUBLISHABLE_KEY || '';

  // Anything env-independent stays here; only ENV/API/Stripe come from Vercel.
  const STATIC = {
    STORAGE_KEYS: {
      AUTH_TOKEN: 'apj_auth_token',
      USER_DATA: 'apj_user_data',
      REFRESH_TOKEN: 'apj_refresh_token',
    },
    VALIDATION: {
      MIN_PASSWORD_LENGTH: 8,
      MIN_NAME_LENGTH: 2,
      MIN_SEARCH_LENGTH: 3,
      DATE_REGEX_SOURCE: '^\\d{4}-\\d{2}-\\d{2}$',
      EMAIL_REGEX_SOURCE: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
      PHONE_REGEX_SOURCE: '^\\+[1-9]\\d{8,14}$',
      COUNTRY_ISO_REGEX_SOURCE: '^[A-Z]{2}$',
    },
    SHIRT_SIZES: {
      Femenino: ['XS', 'S', 'M', 'L'],
      Masculino: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL', '6XL'],
      Otro: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL', '6XL'],
    },
    GENDERS: [
      { value: 'Masculino', label: 'Masculino' },
      { value: 'Femenino', label: 'Femenino' },
      { value: 'Otro', label: 'Otro' },
    ],
    COUNTRIES: [
      { code: 'MX', name: 'Mexico', phone: '+52' },
      { code: 'US', name: 'Estados Unidos', phone: '+1' },
      { code: 'ES', name: 'Espana', phone: '+34' },
      { code: 'AR', name: 'Argentina', phone: '+54' },
      { code: 'CO', name: 'Colombia', phone: '+57' },
      { code: 'CL', name: 'Chile', phone: '+56' },
    ],
  };

  const js = `// Auto-generated by /api/config — do not edit by hand.
const APJConfig = {
  ENV: ${JSON.stringify(ENV)},
  API_BASE_URL: ${JSON.stringify(API_BASE_URL)},
  STRIPE_PUBLISHABLE_KEY: ${JSON.stringify(STRIPE_PUBLISHABLE_KEY)},
  STORAGE_KEYS: ${JSON.stringify(STATIC.STORAGE_KEYS)},
  VALIDATION: {
    MIN_PASSWORD_LENGTH: ${STATIC.VALIDATION.MIN_PASSWORD_LENGTH},
    MIN_NAME_LENGTH: ${STATIC.VALIDATION.MIN_NAME_LENGTH},
    MIN_SEARCH_LENGTH: ${STATIC.VALIDATION.MIN_SEARCH_LENGTH},
    PHONE_REGEX: new RegExp(${JSON.stringify(STATIC.VALIDATION.PHONE_REGEX_SOURCE)}),
    EMAIL_REGEX: new RegExp(${JSON.stringify(STATIC.VALIDATION.EMAIL_REGEX_SOURCE)}),
    DATE_REGEX: new RegExp(${JSON.stringify(STATIC.VALIDATION.DATE_REGEX_SOURCE)}),
    COUNTRY_ISO_REGEX: new RegExp(${JSON.stringify(STATIC.VALIDATION.COUNTRY_ISO_REGEX_SOURCE)})
  },
  SHIRT_SIZES: ${JSON.stringify(STATIC.SHIRT_SIZES)},
  GENDERS: ${JSON.stringify(STATIC.GENDERS)},
  COUNTRIES: ${JSON.stringify(STATIC.COUNTRIES)}
};

Object.freeze(APJConfig);
Object.freeze(APJConfig.STORAGE_KEYS);
Object.freeze(APJConfig.VALIDATION);
Object.freeze(APJConfig.SHIRT_SIZES);
`;

  res.setHeader('Content-Type', 'application/javascript; charset=utf-8');
  // Short cache so a Vercel env var update propagates fast.
  res.setHeader('Cache-Control', 'public, max-age=60, s-maxage=60');
  res.status(200).send(js);
};
